#  ________  ________   _________  ___  ________  ________  ________  ________  ___  ___  _______   ________     
# |\   __  \|\   ___  \|\___   ___\\  \|\   ____\|\   __  \|\   __  \|\   ____\|\  \|\  \|\  ___ \ |\   __  \    
# \ \  \|\  \ \  \\ \  \|___ \  \_\ \  \ \  \___|\ \  \|\  \ \  \|\  \ \  \___|\ \  \\\  \ \   __/|\ \  \|\  \   
#  \ \   __  \ \  \\ \  \   \ \  \ \ \  \ \  \    \ \   _  _\ \   __  \ \_____  \ \   __  \ \  \_|/_\ \   _  _\  
#   \ \  \ \  \ \  \\ \  \   \ \  \ \ \  \ \  \____\ \  \\  \\ \  \ \  \|____|\  \ \  \ \  \ \  \_|\ \ \  \\  \| 
#    \ \__\ \__\ \__\\ \__\   \ \__\ \ \__\ \_______\ \__\\ _\\ \__\ \__\____\_\  \ \__\ \__\ \_______\ \__\\ _\ 
#     \|__|\|__|\|__| \|__|    \|__|  \|__|\|_______|\|__|\|__|\|__|\|__|\_________\|__|\|__|\|_______|\|__|\|__|
#                                                                       \|_________|                             
# For more safe minecraft servers.


###########################################################################################
#                                                                                         #
#                                    Default Settings                                     #
#                                                                                         #
###########################################################################################

# Set log-attempts to true if u want to log every attempt to use the exploit in console
log-attempts: false

# Set log-to-file to true to make it log exploit attempts to a file called LOGS in the same folder as this file
log-to-file: false

# Command to run if someone attempts to abuse the exploit, supports PAPI placeholders, don't include the slash in the command, use %player% for to target the player if you don't have PlaceholderAPI or the Player expansion for it
punish-on-attempt: false
punish-command: ""

###########################################################################################
#                                                                                         #
#                                 Anti-Exploit Settings                                   #
#                                                                                         #
###########################################################################################

# It will be added later :)
