name: AntiCrasher
version: '${project.version}'
main: net.smashyalts.anticrasher.AntiCrasher
api-version: '1.13'
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - PlaceholderAPI